---

- when: apb_action == 'provision'
  block:
    - name: Create directory for cert
      file:
        path: "{{ broker_tls_cert_dir }}"
        state: directory
        mode: 0755
      check_mode: no

    - name: Create cert
      command: >
        openssl req -nodes -x509 -newkey rsa:4096
        -keyout {{ broker_tls_cert_dir }}/key.pem
        -out {{ broker_tls_cert_dir }}/cert.pem
        -days 365
        -subj "/CN={{ broker_name }}.{{ broker_namespace }}.svc"
      args:
        creates: "{{ broker_tls_cert_dir }}/cert.pem"

- name: 'Set tls secret state={{ state }}'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', 'broker-tls.secret.yaml') | from_yaml }}"
