---

{% if cluster == 'kubernetes' %}
apiVersion: v1
kind: Namespace
{% else %}
apiVersion: project.openshift.io/v1
kind: {{ 'Project' if apb_action != 'provision' else 'ProjectRequest' }}
{% endif %}
metadata:
  name: {{ broker_namespace }}
