---

kind: Secret
apiVersion: v1
type: kubernetes.io/tls
metadata:
  name: '{{ broker_tls_name }}'
  namespace: '{{ broker_namespace }}'
{% if apb_action == 'provision' %}
stringData:
  tls.crt: '{{ lookup("file", broker_tls_cert_dir + "/cert.pem" ) }}'
  tls.key: '{{ lookup("file", broker_tls_cert_dir + "/key.pem" ) }}'
{% endif %}
